# https://github.com/prometheus-operator/prometheus-operator/issues/4439#issuecomment-1030198014
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-35.2.0
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    syncOptions:
      - Replace=true
    automated:
      selfHeal: true
      prune: true
